services:
  migrate:
    image: urlshortener
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-migrate
    entrypoint: ["/app/migrate"]
    command: ["up"]
    environment:
      - DB=${DB}
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - default
      - urlshortener-net

  urlshortener:
    depends_on:
      db:
        condition: service_healthy
      redis-db:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    image: urlshortener
    container_name: url-shorted
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "7070:7070"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - DB=${DB}
    networks:
      - default
      - urlshortener-net

  redis-db:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-db
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - default
      - urlshortener-net

  db:
    image: postgres:14-alpine
    container_name: postgres14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default
      - urlshortener-net

volumes:
  database-data:
  redis-data:

networks:
  urlshortener-net:
    external: true