basePath: /
definitions:
  main.GRPCReturn:
    properties:
      message:
        type: string
      status:
        type: string
      url:
        $ref: '#/definitions/urlshortenerpb.ShortenedURL'
    type: object
  main.JSONReturn:
    properties:
      clicks:
        type: integer
      original_url:
        type: string
      shortened_url:
        type: string
    type: object
  main.Response:
    properties:
      grpc:
        $ref: '#/definitions/main.GRPCReturn'
      json:
        $ref: '#/definitions/main.JSONReturn'
      message:
        $ref: '#/definitions/main.message'
    type: object
  main.message:
    properties:
      message:
        type: string
    type: object
  main.shortenBody:
    properties:
      original_url:
        type: string
    type: object
  urlshortenerpb.ShortenedURL:
    properties:
      clicks:
        type: integer
      originalURL:
        type: string
      shortenedURL:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for URL Shortener API.
  title: URL Shortener API
  version: 1.5.0
paths:
  /{pathShort}:
    get:
      description: Redirect to original URL
      operationId: redirect-url
      parameters:
      - description: Shortened URL
        in: path
        name: pathShort
        required: true
        type: string
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.message'
      summary: Redirect to original URL
      tags:
      - redirect
  /info/{pathShort}:
    get:
      consumes:
      - application/json
      description: Get info of URL, choose between json or grpc response, default
        is json, if you want grpc, set return_type to grpc
      operationId: get-info-url
      parameters:
      - description: Info URL
        in: path
        name: pathShort
        required: true
        type: string
      - default: json
        description: Return type
        enum:
        - json
        - grpc
        in: query
        name: return-type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.message'
      summary: Get info of URL
      tags:
      - getinfo
  /shorted:
    post:
      consumes:
      - application/json
      description: Create a shortened URL, choose between json or grpc response, default
        is json, if you want grpc, set return_type to grpc
      operationId: shorten-url
      parameters:
      - description: Original URL
        in: body
        name: original-url
        required: true
        schema:
          $ref: '#/definitions/main.shortenBody'
      - default: json
        description: Return type
        enum:
        - json
        - grpc
        in: query
        name: return-type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.message'
      summary: Shorten URL
      tags:
      - shorten
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
